# Generated by Django 4.2.3 on 2023-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='이미지 링크 URL'),
        ),
    ]
